Controllers/AuthController.cs
using Capstone.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Capstone.Controllers
{
    public class AuthController : Controller
    {
        DBContext db = new DBContext();
        // GET: Auth
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users user)
        {
            var loggedUser = db.Users.Where(u=> u.Email == user.Email && u.Password == user.Password).FirstOrDefault();

            if (loggedUser != null)
            {
                FormsAuthentication.SetAuthCookie(loggedUser.UserId.ToString(), true);
                return RedirectToAction("Index", "Home");
            }

            TempData["ErrorLogin"] = true;
            return RedirectToAction("Login");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/OrdViniController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;
using Newtonsoft.Json;

namespace Capstone.Controllers
{
    public class OrdViniController : Controller
    {
        private DBContext db = new DBContext();

        [Authorize(Roles = "Amministratore")]
        public ActionResult Index()
        {
            var ordArt = db.OrdVini.Include(o => o.Vini).Include(o => o.Ordini);
            return View(ordArt.ToList());
        }
        // GET: OrdVini
        [Authorize(Roles = "Amministratore,Cliente")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ordineWithArticoli = db.OrdVini
                .Include(o => o.Ordini)
                .Include(o => o.Ordini.Users)
                .Include(o => o.Vini)
                .Where(o => o.OrdiniId == id).ToList();

            if (ordineWithArticoli == null)
            {
                return HttpNotFound();
            }

            return View(ordineWithArticoli);
        }

        [HttpPost]
        [Authorize(Roles = "Cliente")]
        public ActionResult AddToCart(int? id)
        {
            //controllo id
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //controllo esistenza Vino
            var vino = db.Vini.FirstOrDefault(v => v.VinoId == id);
            if (vino == null)
            {
                return HttpNotFound();
            }

            //Inizializzazione lista vuota
            List<VinoCart> viniCart = new List<VinoCart>();

            //cookie e controlli
            HttpCookie cartCookie;

            //nel caso sia giá esistente i dati vengono recuperati e deserializzati
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                cartCookie = Request.Cookies["Carrello" + User.Identity.Name];
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
                viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);
            } else
            {
                //altrimenti si crea il cookie e si assegna all'utente
                cartCookie = new HttpCookie("Carrello" + User.Identity.Name);
                cartCookie.Values["User"] = User.Identity.Name; 
            }
            // Se il vino era giá nel carello viene semplicemente incrementato
            var existingCartItem = viniCart.FirstOrDefault(item => item.Vino.VinoId == vino.VinoId);
            if (existingCartItem != null)
            {
                existingCartItem.Quantita++;
            }
            else
            {
                //altrimenti crezione nuovo oggetto e aggiunto a vinoCart
                var vinoCart = new VinoCart()
                {
                    Vino = new Vini()
                    {
                        VinoId = vino.VinoId,
                        Nome = vino.Nome,
                        Prezzo = vino.PrezzoConSconto,
                        Img = vino.Img,
                        Tipo = vino.Tipo,
                        Anno = vino.Anno,
                        Descrizione = vino.Descrizione,
                        Magazzino = vino.Magazzino, //Ridurre qua il numero in magazzino? Fattibile? Senso? 
                        Produttore = vino.Produttore,
                    },
                    Quantita = 1,
                  UserId = Convert.ToInt32(User.Identity.Name),
                };
                viniCart.Add(vinoCart);
            }
            //si serializza la lista
            cartCookie["User"] = HttpUtility.UrlEncode(JsonConvert.SerializeObject(viniCart));
         
            //scadenza del cookie ad un giorno
            cartCookie.Expires = DateTime.Now.AddDays(1); // 1 giorno o piú?

            //Cookie aggiunto alla response e finally reindirizzazione alla home. 
            Response.Cookies.Add(cartCookie);

            return RedirectToAction("Index", "Home"); // Reindirizzare direttamente al carrello? || incentivo all'acquisto?

        }

        [HttpGet]
        [Authorize(Roles = "Cliente")]
        public ActionResult Cart()
        {
            //inizializzazione lista VinoCart
            List<VinoCart> userVinoCart = new List<VinoCart>();

            //verifica esistenza cookie carrello per l'utente loggato
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
                var userId = Convert.ToInt32(User.Identity.Name);

                //Decodifica val cookie & riempie lista
                var viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);

                //Filtra gli articoli in base all'utente loggato
                userVinoCart = viniCart.Where(v => v.UserId == userId).ToList();
                ViewBag.UserCart = userVinoCart;
                ViewBag.Pagamento = new SelectList(db.Pagamenti, "PagamentoId", "TipoPagamento");
            }
            // Ottieni il numero di elementi nel carrello
            int numeroElementiCarrello = userVinoCart.Sum(item => item.Quantita);
            ViewBag.NumeroElementiCarrello = numeroElementiCarrello;
            return View();
        }

        public ActionResult GetNumeroElementiCarrello()
        {
            // Inizializza il numero di elementi nel carrello a 0
            int numeroElementiCarrello = 0;

            // Verifica se esiste un cookie per il carrello per l'utente attualmente autenticato
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                // Decodifica il valore del cookie per ottenere la lista dei prodotti nel carrello
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);

                // Deserializza la lista dei prodotti nel carrello
                var viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);

                // Somma le quantità di tutti i prodotti nel carrello
                numeroElementiCarrello = viniCart.Sum(item => item.Quantita);
            }

            // Restituisci il numero di elementi nel carrello in formato JSON
            return Json(numeroElementiCarrello, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize(Roles = "Cliente")]
        public ActionResult RimuoviDalCarrello(int vinoId)
        {
            var viniCart = new List<VinoCart>();
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
                viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);
            }

            var vinoRemove = viniCart.FirstOrDefault(v => v.Vino.VinoId == vinoId);
            if (vinoRemove != null)
            {
                viniCart.Remove(vinoRemove);
            }

            var cartCookie = new HttpCookie("Carrello" + User.Identity.Name);
            if(viniCart.Any()) //controlla la presenza di articoli nel carrello
            {
                cartCookie.Values["User"] = HttpUtility.UrlEncode(JsonConvert.SerializeObject(viniCart));
                cartCookie.Expires = DateTime.Now.AddDays(1);
            }
            else
            {
                cartCookie.Expires = DateTime.Now.AddDays(-1);
            }
            Response.Cookies.Add(cartCookie);

            return RedirectToAction("Cart");

        }
       
        [HttpPost]
        [Authorize(Roles = "Cliente")]
        [ValidateAntiForgeryToken]

        public ActionResult CreateOrderFromCart(Ordini ordVino)
        {
            // Imposta l'ID dell'utente per l'ordine
            ordVino.UserId = Convert.ToInt32(User.Identity.Name);

            // Recupera il carrello degli acquisti dell'utente corrente
            var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
            var viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);

            // Calcola il totale dell'ordine e aggiorna il magazzino
            decimal totale = 0;
            foreach (var vino in viniCart.Where(a => a.UserId == ordVino.UserId))
            {
                totale += (vino.Quantita * vino.Vino.Prezzo);
                var vinoAcquistato = db.Vini.Find(vino.Vino.VinoId);
                if (vinoAcquistato != null)
                {
                    vinoAcquistato.Magazzino -= vino.Quantita;
                }
            }

            // Imposta lo stato e il totale dell'ordine
            ordVino.Stato = "In Preparazione";
            ordVino.Totale = totale;

           
            db.Ordini.Add(ordVino);
            db.SaveChanges();

            // Ottiene l'ID dell'ordine appena creato
            int newOrdineID = ordVino.OrdiniId;

            // Aggiunge i dettagli dell'ordine nel database
            foreach (var vino in viniCart.Where(a => a.UserId == ordVino.UserId))
            {
                var newOrdVino = new OrdVini
                {
                    VinoId = vino.Vino.VinoId,
                    OrdiniId = newOrdineID,
                    Quantita = Convert.ToInt32(vino.Quantita)
                };
                db.OrdVini.Add(newOrdVino);
            }

            

Controllers/OrdiniController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;

namespace Capstone.Controllers
{
    public class OrdiniController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Ordini
        [Authorize(Roles = "Amministratore")]
        public ActionResult Index()
        {
            var ordini = db.Ordini.Include(o => o.Pagamenti).Include(o => o.Users);
            return View(ordini.ToList());
        }

        // GET: Ordini/Details/5
        [Authorize(Roles = "Cliente, Amministratore")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var idInt = Convert.ToInt32(id);
            var orders = db.Ordini
                         .Where(o => o.UserId == idInt)
                         .OrderByDescending(o => o.OrdiniId) // Ordina per ID in modo decrescente
                         .ToList();

            if (orders == null || orders.Count == 0)
            {
                return HttpNotFound();
            }

            return View(orders);
        }

        // GET: Ordini/Create 

        //public ActionResult Create()
        //{
        //    ViewBag.PagamentoId = new SelectList(db.Pagamenti, "PagamentoId", "TipoPagamento");
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "Nome");
        //    return View();
        //}

        //// POST: Ordini/Create
        //// Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        //// Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "OrdiniId,Indirizzo,Stato,Totale,Consegna,UserId,Nome,Cognome,PagamentoId")] Ordini ordini)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Ordini.Add(ordini);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.PagamentoId = new SelectList(db.Pagamenti, "PagamentoId", "TipoPagamento", ordini.PagamentoId);
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "Nome", ordini.UserId);
        //    return View(ordini);
        //}

        // GET: Ordini/Edit/5
        [Authorize(Roles = "Amministratore")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordini ordini = db.Ordini.Find(id);
            if (ordini == null)
            {
                return HttpNotFound();
            }
            ViewBag.PagamentoId = new SelectList(db.Pagamenti, "PagamentoId", "TipoPagamento", ordini.PagamentoId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Nome", ordini.UserId);
            return View(ordini);
        }

        // POST: Ordini/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Amministratore")]
        public ActionResult Edit(int id, string stato, DateTime consegna)
        {
            var ordine = db.Ordini.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                // Imposta manualmente solo Stato e Consegna
                ordine.Stato = stato;
                ordine.Consegna = consegna;

                db.Entry(ordine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Se il modello non è valido, ricarica le liste e restituisci la vista con l'ordine
            ViewBag.PagamentoId = new SelectList(db.Pagamenti, "PagamentoId", "TipoPagamento", ordine.PagamentoId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Nome", ordine.UserId);
            return View(ordine);
        }

        // GET: Ordini/Delete/5
        [Authorize(Roles = "Amministratore")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordini ordini = db.Ordini.Find(id);
            if (ordini == null)
            {
                return HttpNotFound();
            }
            return View(ordini);
        }

        // POST: Ordini/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Amministratore")]
        public ActionResult DeleteConfirmed(int id)
        {
            Ordini ordini = db.Ordini.Find(id);
            db.Ordini.Remove(ordini);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="~/Stile/Css/StyleHome.css" rel="stylesheet" />
    <style>
        body {
            padding-top: 140px;
        }
    </style>

</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body navbar-custom fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <div style="width: 125px; height: 125px; border-radius: 50%; overflow: hidden;">
                    <img src="~/Stile/Immagini/_010be895-15a4-429d-a858-7a66e320d81e.png" alt="Logo" class="navbar-logo" style="max-height: 100%; width: auto;">
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Noi", "Home")">Su di noi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("DoveTrovarci", "Home")">Dove Trovarci</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Report", "Home")">Per la sostenibilitá</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active btntext-start" aria-current="page" href="@Url.Action("Login", "Auth")">Login</a>
                        </li>

                    }


                    @if (User.IsInRole("Cliente"))
                    {
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Noi", "Home")">Su di noi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("DoveTrovarci", "Home")">Dove Trovarci</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Report", "Home")">Per la sostenibilitá</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Profilo
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("ProfiloUtente", "Profilo")">Il mio profilo</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Details", "Ordini", new { id = User.Identity.Name})">I miei ordini</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Logout", "Auth")">Logout</a></li>
                            </ul>
                        </li>

                    }
                    @if (User.IsInRole("Amministratore"))
                    {
                        <li class="nav-item">@Html.ActionLink("Articoli", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Ordini", "Index", "Ordini", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Logout", "Logout", "Auth", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
                @if (User.IsInRole("Cliente"))
                {

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                        <li class="nav-item">

                            <a href="@Url.Action("Cart", "OrdVini")" class="nav-link">
                                <img id="carrello" src="~/Stile/Immagini/carrello.png" alt="carrello" />
                                <span id="numeroElementiCarrello" class="badge bg-primary"></span>
                            </a>
                        </li>
                    </ul>
                
                }
            </div>
        </div>



    </nav>
    <div class="body-content">
        @RenderBody()
        <footer class="footer navbar-custom">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="text-center">Informazioni</h5>
                        <ul class="list-unstyled text-center">
                            <li><a href="@Url.Action("Noi", "Home")">Chi siamo</a></li>
                            <li><a href="@Url.Action("DoveTrovarci", "Home")">Contatti</a></li>
                            <li><a href="#">Termini e condizioni</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h5 class="text-center">Link Utili</h5>
                        <ul class="list-unstyled text-center">
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#">Politiche aziendali</a></li>
                            <li><a href="#">Recensioni dei clienti</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h5 class="text-center">Seguici</h5>
                        <ul class="list-unstyled social-media-icons text-center">
                            <li><a href="#"><i class="fab fa-facebook-f"></i> Facebook</a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
                            <li><a href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
                        </ul>
                    </div>
                   
                </div>
                <div class="row text-center">
                    <div class="col-md-12">
                        <hr>
                        <p>Una tana per gli amanti del buon vino</p>
                        <p>Orari di apertura: Lun-Ven 9:00-18:00, Sab 9:00-13:00</p>
                        <p>&copy; @DateTime.Now.Year - created by Francesco Missorini</p>
                    </div>
                </div>
            </div>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
   
    <script>
    $(document).ready(function () {
    // Funzione per controllare se la larghezza della finestra è inferiore a 768px (modalità mobile)
    function isMobile() {
        return window.innerWidth < 991;
    }

    // Funzione per mostrare o nascondere l'elemento numeroElementiCarrello
    function updateCartBadgeVisibility() {
        if (data >0 && isMobile()) {
            $("#numeroElementiCarrello").hide();
        } else {
            $("#numeroElementiCarrello").show();
        }
    }

    // Effettua una richiesta AJAX per ottenere il numero di elementi nel carrello
    $.ajax({
        url: "@Url.Action("GetNumeroElementiCarrello", "OrdVini")",
        type: "GET",
        success: function (data) {
            // Verifica se ci sono elementi nel carrello
            if (data > 0) {
                // Aggiorna il contenuto del badge con il numero di elementi nel carrello
                $("#numeroElementiCarrello").text(data);
                // Mostra il badge solo se non sei in modalità mobile
                updateCartBadgeVisibility();
            } else {
                // Nasconde il badge se non ci sono elementi nel carrello
                $("#numeroElementiCarrello").hide();
            }
        },
        error: function () {
            console.error("Errore durante il recupero del numero di elementi nel carrello.");
        }
    });

    // Controlla se la larghezza della finestra cambia per gestire la visibilità del badge in modalità mobile
    $(window).resize(updateCartBadgeVisibility);

    // Gestisci il click sul tasto ad hamburger
    $(".navbar-toggler").click(function () {
        // Verifica se la navbar è stata aperta
        var navbarExpanded = $(this).attr("aria-expanded") === "true";
        // Se la navbar è stata aperta e siamo in modalità mobile, nascondi l'elemento numeroElementiCarrello
        if (navbarExpanded && isMobile()) {
            $("#numeroElementiCarrello").hide();
        }
    });
});
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>