Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;

namespace Capstone.Controllers
{
    public class HomeController : Controller
    {
        private DBContext db = new DBContext();
       
        //GET: Lista Vini
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            return View(db.Vini.ToList());
        }

        public ActionResult Noi()
        {
            return View();
        }

        public ActionResult DoveTrovarci()
        {
            return View();
        }

        public ActionResult Report()
        {
            return View();
        }

        //GET: 
        public ActionResult Dettaglio(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Vini vino = db.Vini.Find(id);

            if (vino == null)
            {
                return HttpNotFound();
            }

            return View(vino);
        }

  

    }
}

Controllers/OrdViniController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;
using Newtonsoft.Json;

namespace Capstone.Controllers
{
    public class OrdViniController : Controller
    {
        private DBContext db = new DBContext();

        [Authorize(Roles = "Amministratore")]
        public ActionResult Index()
        {
            var ordArt = db.OrdVini.Include(o => o.Vini).Include(o => o.Ordini);
            return View(ordArt.ToList());
        }
        // GET: OrdVini
        [Authorize(Roles = "Amministratore,Cliente")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ordineWithArticoli = db.OrdVini
                .Include(o => o.Ordini)
                .Include(o => o.Ordini.Users)
                .Include(o => o.Vini)
                .Where(o => o.OrdiniId == id).ToList();

            if (ordineWithArticoli == null)
            {
                return HttpNotFound();
            }

            return View(ordineWithArticoli);
        }

        [HttpPost]
        [Authorize(Roles = "Cliente")]
        public ActionResult AddToCart(int? id)
        {
            //controllo id
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //controllo esistenza Vino
            var vino = db.Vini.FirstOrDefault(v => v.VinoId == id);
            if (vino == null)
            {
                return HttpNotFound();
            }

            //Inizializzazione lista vuota
            List<VinoCart> viniCart = new List<VinoCart>();

            //cookie e controlli
            HttpCookie cartCookie;

            //nel caso sia giá esistente i dati vengono recuperati e deserializzati
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                cartCookie = Request.Cookies["Carrello" + User.Identity.Name];
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
                viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);
            } else
            {
                //altrimenti si crea il cookie e si assegna all'utente
                cartCookie = new HttpCookie("Carrello" + User.Identity.Name);
                cartCookie.Values["User"] = User.Identity.Name; 
            }
            // Se il vino era giá nel carello viene semplicemente incrementato
            var existingCartItem = viniCart.FirstOrDefault(item => item.Vino.VinoId == vino.VinoId);
            if (existingCartItem != null)
            {
                existingCartItem.Quantita++;
            }
            else
            {
                //altrimenti crezione nuovo oggetto e aggiunto a vinoCart
                var vinoCart = new VinoCart()
                {
                    Vino = new Vini()
                    {
                        VinoId = vino.VinoId,
                        Nome = vino.Nome,
                        Prezzo = vino.PrezzoConSconto,
                        Img = vino.Img,
                        Tipo = vino.Tipo,
                        Anno = vino.Anno,
                        Descrizione = vino.Descrizione,
                        Magazzino = vino.Magazzino, //Ridurre qua il numero in magazzino? Fattibile? Senso? 
                        Produttore = vino.Produttore,
                    },
                    Quantita = 1,
                  UserId = Convert.ToInt32(User.Identity.Name),
                };
                viniCart.Add(vinoCart);
            }
            //si serializza la lista
            cartCookie["User"] = HttpUtility.UrlEncode(JsonConvert.SerializeObject(viniCart));
         
            //scadenza del cookie ad un giorno
            cartCookie.Expires = DateTime.Now.AddDays(1); // 1 giorno o piú?

            //Cookie aggiunto alla response e finally reindirizzazione alla home. 
            Response.Cookies.Add(cartCookie);

            return RedirectToAction("Index", "Home"); // Reindirizzare direttamente al carrello? || incentivo all'acquisto?

        }

        [HttpGet]
        [Authorize(Roles = "Cliente")]
        public ActionResult Cart()
        {
            //inizializzazione lista VinoCart
            List<VinoCart> userVinoCart = new List<VinoCart>();

            //verifica esistenza cookie carrello per l'utente loggato
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
                var userId = Convert.ToInt32(User.Identity.Name);

                //Decodifica val cookie & riempie lista
                var viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);

                //Filtra gli articoli in base all'utente loggato
                userVinoCart = viniCart.Where(v => v.UserId == userId).ToList();
                ViewBag.UserCart = userVinoCart;
                ViewBag.Pagamento = new SelectList(db.Pagamenti, "PagamentoId", "TipoPagamento");
            }
            // Ottieni il numero di elementi nel carrello
            int numeroElementiCarrello = userVinoCart.Sum(item => item.Quantita);
            ViewBag.NumeroElementiCarrello = numeroElementiCarrello;
            return View();
        }

        public ActionResult GetNumeroElementiCarrello()
        {
            // Inizializza il numero di elementi nel carrello a 0
            int numeroElementiCarrello = 0;

            // Verifica se esiste un cookie per il carrello per l'utente attualmente autenticato
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                // Decodifica il valore del cookie per ottenere la lista dei prodotti nel carrello
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);

                // Deserializza la lista dei prodotti nel carrello
                var viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);

                // Somma le quantità di tutti i prodotti nel carrello
                numeroElementiCarrello = viniCart.Sum(item => item.Quantita);
            }

            // Restituisci il numero di elementi nel carrello in formato JSON
            return Json(numeroElementiCarrello, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize(Roles = "Cliente")]
        public ActionResult RimuoviDalCarrello(int vinoId)
        {
            var viniCart = new List<VinoCart>();
            if (Request.Cookies["Carrello" + User.Identity.Name] != null && Request.Cookies["Carrello" + User.Identity.Name]["User"] != null)
            {
                var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
                viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);
            }

            var vinoRemove = viniCart.FirstOrDefault(v => v.Vino.VinoId == vinoId);
            if (vinoRemove != null)
            {
                viniCart.Remove(vinoRemove);
            }

            var cartCookie = new HttpCookie("Carrello" + User.Identity.Name);
            if(viniCart.Any()) //controlla la presenza di articoli nel carrello
            {
                cartCookie.Values["User"] = HttpUtility.UrlEncode(JsonConvert.SerializeObject(viniCart));
                cartCookie.Expires = DateTime.Now.AddDays(1);
            }
            else
            {
                cartCookie.Expires = DateTime.Now.AddDays(-1);
            }
            Response.Cookies.Add(cartCookie);

            return RedirectToAction("Cart");

        }
       
        [HttpPost]
        [Authorize(Roles = "Cliente")]
        [ValidateAntiForgeryToken]

        public ActionResult CreateOrderFromCart(Ordini ordVino)
        {
            // Imposta l'ID dell'utente per l'ordine
            ordVino.UserId = Convert.ToInt32(User.Identity.Name);

            // Recupera il carrello degli acquisti dell'utente corrente
            var cartJson = HttpUtility.UrlDecode(Request.Cookies["Carrello" + User.Identity.Name]["User"]);
            var viniCart = JsonConvert.DeserializeObject<List<VinoCart>>(cartJson);

            // Calcola il totale dell'ordine e aggiorna il magazzino
            decimal totale = 0;
            foreach (var vino in viniCart.Where(a => a.UserId == ordVino.UserId))
            {
                totale += (vino.Quantita * vino.Vino.Prezzo);
                var vinoAcquistato = db.Vini.Find(vino.Vino.VinoId);
                if (vinoAcquistato != null)
                {
                    vinoAcquistato.Magazzino -= vino.Quantita;
                }
            }

            // Imposta lo stato e il totale dell'ordine
            ordVino.Stato = "In Preparazione";
            ordVino.Totale = totale;

           
            db.Ordini.Add(ordVino);
            db.SaveChanges();

            // Ottiene l'ID dell'ordine appena creato
            int newOrdineID = ordVino.OrdiniId;

            // Aggiunge i dettagli dell'ordine nel database
            foreach (var vino in viniCart.Where(a => a.UserId == ordVino.UserId))
            {
                var newOrdVino = new OrdVini
                {
                    VinoId = vino.Vino.VinoId,
                    OrdiniId = newOrdineID,
                    Quantita = Convert.ToInt32(vino.Quantita)
                };
                db.OrdVini.Add(newOrdVino);
            }

            

Controllers/VinisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;

namespace Capstone.Controllers
{
    public class VinisController : Controller
    {
        private DBContext db = new DBContext();

     


        // GET: Vinis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vini vini = db.Vini.Find(id);
            if (vini == null)
            {
                return HttpNotFound();
            }
            return View(vini);
        }

        // GET: Vinis/Create
        [Authorize(Roles = "Amministratore")]

        public ActionResult Create()
        {
            return View();
        }

        // POST: Vinis/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Amministratore")]
        public ActionResult Create([Bind(Include = "VinoId,Nome,Img,Tipo,Anno,Descrizione,Prezzo,Magazzino,Produttore,SottoTipo,Sconto")] Vini vini)
        {
            if (ModelState.IsValid)
            {
                db.Vini.Add(vini);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vini);
        }

        // GET: Vinis/Edit/5
        [Authorize(Roles = "Amministratore")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vini vini = db.Vini.Find(id);
            if (vini == null)
            {
                return HttpNotFound();
            }
            return View(vini);
        }

        // POST: Vinis/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Amministratore")]
        public ActionResult Edit([Bind(Include = "VinoId,Nome,Img,Tipo,Anno,Descrizione,Prezzo,Magazzino,Produttore,SottoTipo,Sconto")] Vini vini)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vini).State = EntityState.Modified;
                db.SaveChanges();
                // Reindirizza l'utente alla pagina Index del controller Home
                return RedirectToAction("Index", "Home");
            }
            return View(vini);
        }

        // GET: Vinis/Delete/5
        [Authorize(Roles = "Amministratore")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vini vini = db.Vini.Find(id);
            if (vini == null)
            {
                return HttpNotFound();
            }
            return View(vini);
        }

        // POST: Vinis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Amministratore")]
        public ActionResult DeleteConfirmed(int id)
        {
            Vini vini = db.Vini.Find(id);
            db.Vini.Remove(vini);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/Dettaglio.cshtml
@model Capstone.Models.Vini

@{
    ViewBag.Title = "Dettaglio";
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="@Model.Img" alt="Immagine" class="img-fluid mb-3" />
        </div>
        <div class="col-md-6">
            <h2>@Model.Nome</h2>
            @if (Model.Sconto != null)
            {
                var prezzoScontato = Model.Prezzo - (Model.Prezzo * (decimal)Model.Sconto / 100);
                <p>Prezzo: <span style="color: red;">@prezzoScontato.ToString("0.##") €</span> (@Model.Sconto % di sconto)</p>
                <p>Prezzo Originale: <del>@Model.Prezzo €</del></p>
            }
            else
            {
                <p>Prezzo: @Model.Prezzo €</p>
            }
            <p>Descrizione: @Model.Descrizione</p>
            <p>Tipo: @Model.Tipo</p>
            <p>Produttore: @Model.Produttore</p>
            @if (User.Identity.IsAuthenticated)
            {
                using (Html.BeginForm("AddToCart", "OrdVini", new { id = Model.VinoId }, FormMethod.Post))
                {
                    if (Model.Magazzino > 0)
                    {
                        <input type="submit" value="Aggiungi all'ordine" class="btn btn-success" />
                    }
                    else
                    {
                        <p style="color: red;">Prodotto non disponibile</p>
                    }
                }
            }
            else
            {
                <p style="color: red;">Esegui il login per acquistare</p>
            }
        </div>
    </div>
</div>

Views/Home/DoveTrovarci.cshtml
@{
    ViewBag.Title = "Dove Trovarci";
}

<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Stile/Css/StyleHome.css" rel="stylesheet" />

    <style>
        body {
            background-image: url('../../stile/immagini/wood-wine-barrels-stored-winery-fermentation-process.jpg');
            background-size: cover; /* Imposta l'immagine di sfondo per coprire l'intera area del body */
            background-position: center; /* Centra l'immagine di sfondo */
            background-repeat: no-repeat; /* Impedisce la ripetizione dell'immagine di sfondo */
            background-attachment: fixed; /* Fissa l'immagine di sfondo in modo che non scorra con il contenuto */
            margin: 0; /* Rimuove i margini per centrare correttamente il contenuto */
            padding: 0; /* Rimuove il padding per centrare correttamente il contenuto */
        }

 

        h2 {
            text-align: center;
            color: #8B0000;
            margin-top: 30px; /* Aggiunge spazio in alto */
        }

        
    </style>
</head>
<body>
    <h2>Dove Trovarci</h2>

    <div class="map-container">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d6596.427911973707!2d12.980457539612981!3d45.96214523067146!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sit!2sit!4v1713339966142!5m2!1sit!2sit" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="location-info">
        <h3>Siamo Qui</h3>
        <p>Vieni a trovarci presso il nostro punto vendita in:</p>
        <p>Via Roma, 69 - Codroipo</p>
        <p>Siamo aperti nei seguenti orari:</p>
        <ul>
            <li>Lunedì - Venerdì: 9:00 - 18:00</li>
            <li>Sabato: 9:00 - 13:00</li>
            <li>Domenica: Chiuso</li>
        </ul>
        <p>Per maggiori informazioni, contattaci al numero: +39 0123 456789</p>
    </div>
</body>
</html>

Views/Home/Index.cshtml
@model IEnumerable<Capstone.Models.Vini>

@if (User.IsInRole("Amministratore"))
{
   <div class="container">
       <div class="text-center mt-4">
           @if (User.IsInRole("Amministratore"))
           {
               @Html.ActionLink("Aggiungi Nuovo Articolo", "Create", "Vinis", null, new { @class = "btn btn-primary btn-lg mb-4" })
           }
       </div>
       <div class="d-none d-md-block">
           <!-- Nascondi la tabella su dispositivi mobili -->
           <div class="table-responsive">
               <table class="table table-bordered table-striped">
                   <thead class="thead-dark">
                       <tr>
                           <th scope="col">Nome</th>
                           @if (User.IsInRole("Amministratore"))
                           {
                               <th scope="col">Immagine</th>
                               <th scope="col">Prezzo</th>
                               <th scope="col">Magazzino</th>
                               <th scope="col">Azioni</th>
                           }
                       </tr>
                   </thead>
                   <tbody>
                       @foreach (var item in Model)
                       {
                           <tr>
                               <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                               @if (User.IsInRole("Amministratore"))
                               {
                                   <td>
                                      <img src="@item.Img" class="img img-fluid" alt="@item.Nome" style="max-width: 100px;">
                                   </td>
                                   <td>@Html.DisplayFor(modelItem => item.Prezzo) €</td>
                                   <td>@Html.DisplayFor(modelItem => item.Magazzino)</td>
                                   <td>
                                       <div class="btn-group" role="group" aria-label="Actions">
                                           @Html.ActionLink("Dettagli", "Details", "Vinis", new { id = item.VinoId }, new { @class = "btn btn-secondary btn-sm" })
                                           @Html.ActionLink("Modifica", "Edit", "Vinis", new { id = item.VinoId }, new { @class = "btn btn-info btn-sm" })
                                           <a href="@Url.Action("Delete", "Vinis", new { id = item.VinoId })" class="btn btn-danger btn-sm" title="Cancella">
                                               <span class="fas fa-trash-alt" style="line-height: 1;"></span>
                                           </a>
                                       </div>
                                   </td>
                               }
                           </tr>
                       }
                   </tbody>
               </table>
           </div>
       </div>
       <div class="d-md-none">
           <!-- Visualizza i dati come lista su dispositivi mobili -->
           <ul class="list-group">
               @foreach (var item in Model)
               {
                   <li class="list-group-item">
                       <div>@Html.DisplayFor(modelItem => item.Nome)</div>
                       @if (User.IsInRole("Amministratore"))
                       {
                           <div class="text-center">
                               <!-- Centra l'immagine su dispositivi mobili -->
                               <img src="@item.Img" class="img-fluid " alt="@item.Nome" style="max-width: 100px;">
                           </div>
                           <div>Prezzo: @Html.DisplayFor(modelItem => item.Prezzo) €</div>
                           <div>Magazzino: @Html.DisplayFor(modelItem => item.Magazzino)</div>
                           <div>
                               <div class="btn-group" role="group" aria-label="Actions">
                                   @Html.ActionLink("Dettagli", "Details", "Vinis", new { id = item.VinoId }, new { @class = "btn btn-secondary btn-sm" })
                                   @Html.ActionLink("Modifica", "Edit", "Vinis", new { id = item.VinoId }, new { @class = "btn btn-info btn-sm" })
                                   <a href="@Url.Action("Delete", "Vinis", new { id = item.VinoId })" class="btn btn-danger btn-sm" title="Cancella">
                                       <span class="fas fa-trash-alt" style="line-height: 1;"></span>
                                   </a>
                               </div>
                           </div>
                       }
                   </li>
               }
           </ul>
       </div>
   </div>
}

else
{
<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://www.vinatis.it/img/slider/new/1381" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">

            </div>
        </div>
        <div class="carousel-item">
            <img src="https://resources.vino.com/data/slideshowItemImmagine/slideshowItemImmagine-6003.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Etichette prestigiose</h5>
                <p>Una vasta scelta di bottiglie da tutto il mondo.</p>
            </div>
        </div>
        <div class="carousel-item">
            <video class="video-fluid d-block mx-auto w-75" autoplay loop controls style="max-width: 100%;">
                <source src="~/Stile/Immagini/Pubblicit%c3%a0_Banner.mp4" type="video/mp4" />
                Your browser does not support the video tag.
            </video>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>

</div>
    <div>
        <div class="text-center mt-4 ">
            <a href="@Url.Action("ViniPerTipo", "OrdVini", new { tipo = "Rosso" })" id="BottoneRicerca" class="btn btn-lg mb-2">Vini Rossi</a>
            <a href="@Url.Action("ViniPerTipo", "OrdVini", new { tipo = "Bianco" })" id="BottoneRicerca" class="btn btn-lg mb-2">Vini Bianchi</a>
            <a href="@Url.Action("ViniPerTipo", "OrdVini", new { tipo = "Prosecco" })" id="BottoneRicerca" class="btn btn-lg mb-2">Prosecco</a>
            <a href="@Url.Action("ViniPerTipo", "OrdVini", new { Tipo = "Spirits", sottoTipo = "Rum" })" id="BottoneRicerca" class="btn  btn-lg mb-2">Rum</a>
            <a href="@Url.Action("ViniPerTipo", "OrdVini", new { Tipo = "Spirits", sottoTipo = "Gin" })" id="BottoneRicerca" class="btn btn-lg mb-2">Gin</a>
            <a href="@Url.Action("ViniPerTipo", "OrdVini", new { tipo = "Champagne" })" id="BottoneRicerca" class="btn btn-lg mb-2">Champagne</a>
        </div>
    </div>
    <div class="container">
        <form class="search-form mb-4" action="@Url.Action("Search", "OrdVini")" method="get">
            <div class="input-group">
                <input type="text" class="form-control" name="searchTerm" placeholder="Con cosa ti ubriacherai oggi...?" />
                <div class="input-group-append">
                    <button id="BottoneRicerca" type="submit" class="btn">Cerca</button>
                </div>
            </div>
        </form>

        <h2 class="text-center mb-4">Le nostre bottiglie pregiate</h2>


        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
            @foreach (var item in Model)
            {
                <div class="col mb-4">
                    <div class="card h-100">
                        <a href="@Url.Action("Dettaglio", "Home", new { id = item.VinoId })">
                            <img src="@item.Img" class="card-img-top" alt="@item.Nome">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">@item.Nome</h5>
                            @if (item.Sconto != null)
                            {
                                <p class="card-text">Prezzo: <span style="color: red;">@item.PrezzoConSconto.ToString("0.##") €</span> (@item.Sconto % di sconto)</p>
                                <p class="card-text">Prezzo Originale: <del>@item.Prezzo €</del></p>
                            }
                            else
                            {
                                <p class="card-text">Prezzo: @item.Prezzo €</p>
                            }
                        </div>
                    </div>

                </div>
            }
        </div>

    </div>
}